import styles from "../../styles/Pages/Form/Login.module.scss";
import {useEffect, useState} from "react";
import Register from "../../Component/Form/Register";
import {useRouter} from "next/router";
import Login from "../../Component/Form/Login";
import {useSession} from "next-auth/react";
import ForgotPassword from "../../Component/Form/ForgotPassword";
import ResetPasswordForm from "../../Component/Form/ResetPassword";
import Head from "next/head";


export async function getServerSideProps({req,query}){

    if(!query.token || !query.email || !query.id){
        return {
            redirect: {
                permanent: false,
                destination: "/",
            },
        }
    }

    return {
        props:{
            ressources: query
        }
    }
}

const ResetPassword = ({ressources}) => {

    const router = useRouter();

        return (

            <div className={styles.container}>
                <Head>
                    <title>Réinitialisation du mot de passe</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={styles.content}>
                    <ResetPasswordForm
                        id={ressources.id}
                        email={ressources.email}
                        token={ressources.token}
                    />
                </div>
            </div>
        )
}
export default ResetPassword;