import styles from '../../styles/Pages/email-verification/EmailError.module.scss';
import anim from '../../styles/utils/anim.module.scss';
import {useRouter} from "next/router";
import Head from "next/head";
import React from "react";
import {GetImgPathOfAssets} from "../../utils/ImageUtils";

const AuthError = () => {
    const router = useRouter();
    return (
        <div className={styles.container + ' ' + anim.fadeIn}>
            <Head>
                <title>Erreur - Authentification</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <img
                    alt={'Image Old Ogla'}
                onError={(e) => e.target.src = '/assets/diapo/old.png'}
                src={GetImgPathOfAssets() + 'diapo/old.png'}/>


            <h1>Impossible de vous authentifier</h1>
           <p style={{
               fontWeight:'bold',
           }}>
               Désolé, mais nous n'avons pas réussi à vous connecter. <br/>Cela peut être dû à une erreur d'authentification ou à une suspension de votre compte pour non-conformité.
           </p>
        </div>
    )
}

export default AuthError;