import styles from '../../../styles/Pages/Dashboard/Support.module.scss';
import VerticalAuthorMenu from "../../../Component/Menu/VerticalAuthorMenu";
import HeaderDashboard from "../../../Component/Dashboard/HeaderDashboard";
import SmHeaderDashboard from "../../../Component/Dashboard/SmHeaderDashboard";
import VerticalPhoneMenu from "../../../Component/Menu/VerticalPhoneMenu";
import VerticalTabMenu from "../../../Component/Menu/VerticalTabMenu";
import ScreenSize from "../../../utils/Size";
import useOrientation from "../../../utils/Orientation";
import Head from "next/head";
import React from "react";
import {GetImgPathOfAssets} from "../../../utils/ImageUtils";

const Support = () => {

    const [width, height] = ScreenSize();
    const orientation = useOrientation();

    return (
        <div className={styles.container}>
            <Head>
                <title>Support</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.containerMain}>
                {
                    width < 700 && orientation === 'portrait' ?
                        <VerticalPhoneMenu/>
                        :
                        <>
                            {
                                width >= 700 && width <= 1050 ?
                                    <div className={styles.verticalTabContainer}>
                                        <VerticalTabMenu/>
                                    </div>
                                    :
                                    <div className={styles.verticalMenuContainer}>
                                        <VerticalAuthorMenu/>
                                    </div>
                            }
                        </>

                }
                <div className={styles.containerData}>
                    <SmHeaderDashboard title={'Support'}/>
                    <div className={styles.supportContainer}>
                        <img alt={'Montagne Livre Ogla'} onError={(e) => e.target.src = '/assets/diapo/mountain6.png'}
                             src={GetImgPathOfAssets() + 'diapo/mountain6.png'}/>
                        <h3>Contactez nous</h3>
                        <p>Pour toute question ou problème technique, contactez notre équipe de support sur <span
                            className={styles.twitter}>Twitter</span> ou à l&apos;adresse suivante : <strong><a
                            href={'mailto:support@ogla.fr?subject=Demande d\'assistance Ogla'}>support@ogla.fr</a>
                        </strong></p>
                    </div>
                </div>

            </div>

        </div>
    )
}

export default Support;