import styles from '../../../styles/Pages/email-verification/EmailError.module.scss';
import {useRouter} from "next/router";
import Head from "next/head";

const ExpiredEmail = () => {
    const router = useRouter();
    return (
        <div className={styles.container}>
            <Head>
                <title>Réinitialisation du mot de passe</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <img src={'/assets/diapo/mountain.png'}/>
            <h1>Désolé</h1>
            <p>Le lien pour modifier votre mot de passe a expiré. Veuillez <span className={styles.retry} onClick={() =>{
                router.replace({
                    pathname:'/auth',
                    query:'forgotPassword'
                })
            } }>réessayer</span></p>
            <button onClick={() => router.replace('/')}>Accueil</button>
        </div>
    )
}

export default ExpiredEmail;