import styles from '../../../styles/Pages/email-verification/EmailError.module.scss';
import anim from '../../../styles/utils/anim.module.scss';
import {useRouter} from "next/router";
import Head from "next/head";
import React from "react";
import {GetImgPathOfAssets} from "../../../utils/ImageUtils";

const ExpiredEmail = () => {
    const router = useRouter();
    return (
        <div className={styles.container + ' ' + anim.fadeIn}>
            <Head>
                <title>Ogla - Email vérification</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <img
                alt={'Image Expire Ogla'}
                onError={(e) => e.target.src = '/assets/diapo/old.png'}
                src={GetImgPathOfAssets() + 'diapo/old.png'}/>
            <h1>Oups !</h1>
            <p>Le lien de vérification a expiré. Veuillez demander une nouvelle vérification...</p>
            <button onClick={() => router.replace('/')}>Accueil</button>
        </div>
    )
}

export default ExpiredEmail;