import styles from '../../../styles/Pages/email-verification/EmailError.module.scss';
import {useRouter} from "next/router";
import Head from "next/head";
import React from "react";

const ExpiredEmail = () => {
    const router = useRouter();
    return (
        <div className={styles.container}>
            <Head>
                <title>Ogla - Email vérification</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <img src={'/assets/diapo/mountain.png'}/>
            <h1>Désolé...</h1>
            <p>Le lien de vérification <strong>OGLA </strong> a expiré. Veuillez demander une nouvelle vérification...</p>
            <button onClick={() => router.replace('/')}>Accueil</button>
        </div>
    )
}

export default ExpiredEmail;