import Head from 'next/head'
import styles from '../styles/Home.module.scss';
import anim from '../styles/utils/anim.module.scss';
import Header from "../Component/Header";
import Banner from "../Component/Banner";
import Footer from "../Component/Footer";
import {HotPostPhone, HotPost} from "../Component/Post/HotPost";
import {ChevronDoubleRightIcon} from "@heroicons/react/20/solid";
import PreviewHorizontalPostList from "../Component/Post/PreviewHorizontalPostList";
import CategoryHome from "../Component/CategoryHome";
import React, {Fragment, useContext, useEffect, useState} from "react";
import {useSession} from "next-auth/react";
import {LoginModal} from "../Component/Modal/LoginModal";
import {GetTopBooksOnHomeApi} from "./api/book";
import {GetActiveMonthlyCateoryApi} from "./api/Category";
import {Capitalize} from "../utils/String";
import {useRouter} from "next/router";
import {BannerBecameWriter} from "../Component/BannerBecameWriter";

import MusicHome from '../Component/MusicHome';
import {DeleteAllNotifsService} from '../service/Notifications/NotificationsService';
import ScreenSize from "../utils/Size";
import HeaderResponsive from '../Component/HeaderResponsive';
import {HeaderHome} from "../Component/HeaderHome";
import {toastDisplayTest} from "../utils/Toastify";
import {HeaderMainResponsive} from "../Component/HeaderMainResponsive";
import {Partner} from "../Component/Partner";
import NewFeatured from "../Component/Category/New";

export async function getServerSideProps() {
    const cat = await GetActiveMonthlyCateoryApi();
    let data;
    if (!cat.err) {
        data = await GetTopBooksOnHomeApi(cat.data.fCat, cat.data.sCat);
    } else {
        data.err = true;
        return {
            props: {
                err: true,
            }
        }
    }

    return {
        props: {
            err: data.err,
            tops: data.tops,
            firstTopBooks: data.firstTop,
            secondTopBooks: data.secondTop,
            cat1: cat.data.fCat,
            cat2: cat.data.sCat
        }
    }
}

export default function Home({tops, firstTopBooks, secondTopBooks, cat1, cat2, err}) {

    const {data: session} = useSession();
    const [width, height] = ScreenSize();

    const router = useRouter();


    return (
        <div className={styles.container + ' ' + anim.fadeIn}>
            <Head>
                <title>Ogla</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {
                width > 950 ?
                    <div className={styles.header}>
                        <HeaderHome/>
                    </div> :
                    <HeaderMainResponsive/>
            }

            <Banner/>
            <CategoryHome/>
            {
                !err && tops && tops.length === 2 &&
                <div className={styles.hot}>
                    <div className={styles.headerHot}>
                        <h4>Populaires :</h4>
                        <h5 tabIndex={0} onClick={() => router.push({pathname: '/cat'})}>Tout
                            voir <ChevronDoubleRightIcon/></h5>
                    </div>

                    <div className={styles.hotContainer}>
                        {
                            width > 450 ?
                                <>
                                    {
                                        tops.map((item, i) => {

                                            return (
                                                <Fragment key={item._id}>
                                                    <HotPost
                                                        className={styles.hotItem}
                                                        authorImg={item.author.img}
                                                        id={item?._id}
                                                        slug={item?.slug}
                                                        likes={item?.likes}
                                                        top={i === 0}
                                                        title={item?.title} nbChapter={item?.nbChapters}
                                                        author={item?.author_pseudo}
                                                        img={item?.img} category={item?.category}
                                                        description={item?.summary}
                                                    />
                                                </Fragment>

                                            )
                                        })
                                    }

                                </>
                                :
                                <>
                                    {
                                        tops.map((item, i) => {
                                            return (
                                                <Fragment key={item._id}>
                                                    <HotPostPhone className={styles.hotItem}
                                                                  id={tops[i]?._id}
                                                                  slug={tops[i]?.slug}
                                                                  likes={tops[i]?.likes}
                                                                  top={true}
                                                                  title={tops[i]?.title} nbChapter={tops[i]?.nbChapters}
                                                                  author={tops[i]?.author_pseudo}
                                                                  img={tops[i]?.img} category={tops[i]?.category}
                                                                  description={tops[i]?.summary}
                                                    />
                                                </Fragment>

                                            )
                                        })
                                    }
                                </>
                        }


                    </div>
                    {
                        firstTopBooks.length !== 0 && secondTopBooks.length !== 0 &&
                        <>
                            <h5 className={styles.trendTitle}>Qu&apos;est ce qu&apos;on lit chez <strong>OGLA</strong> ?
                            </h5>

                            <div className={styles.previewPostListContainer}>
                                <PreviewHorizontalPostList list={firstTopBooks} title={'Tendance ' + cat1}/>
                                <div className={styles.sep}> </div>
                                <PreviewHorizontalPostList list={secondTopBooks} title={'Tendance ' + cat2}/>
                            </div>
                        </>
                    }
                </div>
            }

            <BannerBecameWriter/>
            <MusicHome/>
            <Partner/>

            <Footer/>

        </div>
    )
}
