import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Header from "../Component/Header";
import Banner from "../Component/Banner";
import Footer from "../Component/Footer";
import HotPost from "../Component/Post/HotPost";
import {ChevronDoubleRightIcon} from "@heroicons/react/20/solid";
import PreviewHorizontalPostList from "../Component/Post/PreviewHorizontalPostList";
import CategoryHome from "../Component/CategoryHome";
import React, {useContext, useEffect, useState} from "react";
import {ConfigBearer, getAccessToken, GetBearerConfig, getConfigOfProtectedRoute} from "./api/utils/Config";
import {useSession} from "next-auth/react";
import {LoginModal} from "../Component/Modal/LoginModal";
import {GetTopBooksOnHomeApi} from "./api/book";
import {GetActiveMonthlyCateoryApi} from "./api/Category";
import {Capitalize} from "../utils/String";
import {useRouter} from "next/router";

export async function getServerSideProps() {
    const cat = await GetActiveMonthlyCateoryApi();
    let data;
    if (!cat.err) {
        data = await GetTopBooksOnHomeApi(cat.data.fCat, cat.data.sCat);
    }

    console.log(cat.data)
    return {
        props: {
            err: data.err,
            tops: data.tops,
            firstTopBooks: data.firstTop,
            secondTopBooks: data.secondTop,
            cat1: cat.data.fCat,
            cat2: cat.data.sCat
        }
    }
}


export default function Home({tops, firstTopBooks, secondTopBooks, cat1, cat2}) {

    const {data: session} = useSession();
    const router = useRouter();

    return (

        <div className={styles.container}>
            <Head>
                <title>Ogla - Une histoire d'écrivain</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div
                /** style={{
                 position: "fixed",
                 top: 0,
                 zIndex: 2,
                 width: "100%"
             }*/>
                <Header/>

            </div>
            <Banner/>
            <CategoryHome/>
            <div className={styles.hot}>
                <div className={styles.headerHot}>
                    <h4>Populaires :</h4>
                    <h5 onClick={() => router.push({pathname:'/cat'})}>Tout voir <ChevronDoubleRightIcon/></h5>
                </div>
                <div className={styles.hotContainer}>
                    <HotPost className={styles.hotItem}
                             likes={tops[0].likes}
                             top={true}
                             title={tops[0].title} nbChapter={tops[0].nbChapters} author={tops[0].author_pseudo}
                             img={tops[0].img} category={tops[0].category}
                             description={tops[0].summary}
                    />
                    <HotPost className={styles.hotItem}
                             likes={tops[1].likes}
                             top={false}
                             title={tops[1].title} nbChapter={tops[1].nbChapters} author={tops[1].author_pseudo}
                             img={tops[1].img} category={tops[1].category}
                             description={tops[1].summary}
                    />

                </div>

                <h7 className={styles.trendTitle}>Qu'est ce qu'on lit chez <strong>OGLA</strong> ?</h7>


                <div className={styles.previewPostListContainer}>
                    <PreviewHorizontalPostList list={firstTopBooks} title={'Tendance '+ cat1} type={"Horreur"}/>
                    <PreviewHorizontalPostList list={secondTopBooks} title={'Tendance ' +cat2} type={"Horreur"}/>
                </div>

            </div>
            <Footer></Footer>
            <LoginModal close={() => alert('kek')}/>

        </div>
    )
}
