import styles from "../../styles/Pages/Dashboard/Books.module.scss";
import VerticalAuthorMenu from "../../Component/Menu/VerticalAuthorMenu";
import {useRouter} from "next/router";
import {useSession} from "next-auth/react";
import {getConfigOfProtectedRoute} from "../api/utils/Config";
import HeaderDashboard from "../../Component/Dashboard/HeaderDashboard";
import Head from "next/head";
import React from "react";

export default function DashboardAuthor() {

    const router = useRouter();
    const {data: session} = useSession();

    return (
            <div className={styles.container}>
                <Head>
                    <title>Tableau de bord</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            <div className={styles.containerMain}>
                <div className={styles.verticalMenuContainer}>
                    <VerticalAuthorMenu/>
                </div>
                <div className={styles.containerData}>
                    <HeaderDashboard/>
                </div>

            </div>

        </div>
    )
}